# Generated by Django 5.0.1 on 2026-01-14 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Новый заказ'), ('order_cancelled', 'Заказ отменен'), ('order_updated', 'Заказ обновлен'), ('order_taken', 'Заказ взят'), ('order_completed', 'Заказ завершен')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
