# Generated by Django 5.0.1 on 2026-01-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_client', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для клиента')),
                ('price_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для водителя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cars.carclass', verbose_name='Класс автомобиля')),
                ('zone_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_from', to='pricing.zone', verbose_name='Откуда')),
                ('zone_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_to', to='pricing.zone', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['zone_from', 'zone_to', 'car_class'],
                'unique_together': {('zone_from', 'zone_to', 'car_class')},
            },
        ),
    ]
