# Generated by Django 5.0.1 on 2026-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='center_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта центра'),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота центра'),
        ),
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(default='#3b82f6', help_text='Цвет в формате HEX (например, #3b82f6)', max_length=7, verbose_name='Цвет на карте'),
        ),
        migrations.AddField(
            model_name='zone',
            name='geometry',
            field=models.JSONField(blank=True, help_text='Координаты полигона в формате GeoJSON', null=True, verbose_name='Геометрия (GeoJSON)'),
        ),
    ]
