# Generated by Django 5.0.1 on 2026-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='Push подписка (JSON)'),
        ),
    ]
