# Generated by Django 5.0.1 on 2026-01-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200, verbose_name='ФИО пассажира')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='Телефон пассажира')),
                ('passenger_count', models.IntegerField(default=1, verbose_name='Количество пассажиров')),
                ('address_from', models.TextField(blank=True, verbose_name='Адрес откуда (детали)')),
                ('address_to', models.TextField(blank=True, verbose_name='Адрес куда (детали)')),
                ('pickup_time', models.DateTimeField(verbose_name='Время подачи')),
                ('direction', models.CharField(choices=[('oneway', 'Только туда'), ('roundtrip', 'Туда и обратно')], default='oneway', max_length=20, verbose_name='Направление')),
                ('flight_number', models.CharField(blank=True, max_length=50, verbose_name='Номер рейса')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('price_client', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для клиента')),
                ('price_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для водителя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает водителя'), ('taken', 'Взят водителем'), ('in_progress', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Взят водителем')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнен')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.carclass', verbose_name='Класс автомобиля')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
