# Generated by Django 5.0.1 on 2026-01-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('orders', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='zone_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='pricing.zone', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='order',
            name='zone_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='pricing.zone', verbose_name='Куда'),
        ),
    ]
